Scalar = Union{Number,Nothing}
List = Union{AbstractVector,AbstractSet,Tuple}
Container = Union{List,AbstractArray}
Map = Union{AbstractDict,NamedTuple}
Collection = Union{Container,Map}
Str = Union{Symbol,AbstractChar,AbstractString}
Index = Union{S,Colon,UnitRange{T}} where {S<:Integer,T<:Integer}
Func = Union{Function,Type}
VectorField = Union{AbstractVector,Map}