Scalar = Union{Number,Nothing,Missing,AbstractString,Symbol}
List = Union{AbstractVector,AbstractSet,Tuple}
ArrayLike = Union{List,AbstractArray}
Map = Union{AbstractDict,NamedTuple}
Collection = Union{ArrayLike,Map}
Str = Union{Symbol,AbstractChar,AbstractString}
Index = Union{S,Colon,UnitRange{T}} where {S<:Integer,T<:Integer}
Func = Union{Function,Type}
VectorField = Union{AbstractVector{<:AbstractArray},Map}